In [5]:
import numpy as np
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])
C = A + B
print("A + B =\n", C)

D = A-B
print("A - B=\n",D)

E = np.dot(A, B)
print("A * B (dot product) =\n", E)

print("Transpose of A:\n", A.T)





A + B =
 [[ 6  8]
 [10 12]]
A - B=
 [[-4 -4]
 [-4 -4]]
A * B (dot product) =
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
